name: Deploy React App

# Dispara sempre que houver push na branch main
# E somente se houver alteração na pasta ktecnolead/
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Pega o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. Instala dependências e faz build do React
      - name: Build React app
        run: |
          npm install
          CI=false npm run build

      # 4. Deploy via SCP para VPS
      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.2
        with:
          host: 72.60.59.149
          username: root
          key: ${{ secrets.VPS_KEY }}
          port: 22
          source: "dist/**"
          target: "/var/www/front_lead_tmp"
          strip_components: 1

      # 5. Swap de pastas no VPS via SSH
      - name: Swap folders on VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 72.60.59.149
          username: root
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            rm -rf /var/www/front_lead_old
            if [ -d /var/www/front_lead ]; then mv /var/www/front_lead /var/www/front_lead_old; fi
            if [ -d /var/www/front_lead_tmp ]; then mv /var/www/front_lead_tmp /var/www/front_lead; fi
